name: Julien Eyriès home page
title: Julien Eyriès
description: My home page
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
show_excerpts: false
header_pages:
  - cv.html
minima:
  social_links:
    twitter: jeyries
    github: jeyries
    linkedin: julieneyries
