name: Julien Eyriès blog
title: Julien Eyriès blog
description: Julien Eyriès blog
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: minima
show_excerpts: true
minima:
  social_links:
    twitter: jeyries
    github: jeyries
    linkedin: julieneyries
